accountapp/urls.py
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, test
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accountapp'

urlpatterns = [
    path('test/', test, name='test'),                           # 두 번째 인자 test는 함수형 view => 이 경우에는 해당 함수이름을 바로 써서 넣어주면 되지만
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),  # class based view는 as_view()를 적어줘야 한다
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

mureojwo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("accounts/", include("allauth.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("commentapp/", include("commentapp.urls")),
    path("likes/", include("likeapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name = 'profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from accountapp.models import HelloWorld
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from accountapp.forms import AccountUpdateForm

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import account_ownership_required

has_ownership = [account_ownership_required, login_required]

# Create your views here.
@login_required
def test(request):

    if request.method == "POST":
        temp = request.POST.get('test_input')
        test_text = HelloWorld()
        test_text.text = temp
        test_text.save()  
        return HttpResponseRedirect(reverse('accountapp:test'))
    
    else:
        new_text_list = HelloWorld.objects.all()
        return render(request, 'accountapp/test.html', context={'new_text_list':new_text_list})
    
    


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login') # reverse와 reverse_lazy의 차이점? => reverse_lazy는 class형 view에서 사용한다(class에서는 reverse를 사용할 수 없음)
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:detail')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}


{% block content%}

<div class="account_create_base">
    <div>
        <h4>회원가입</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary rounded-pill col-6 mt-3">
    </form>
    <hr>
    <div>
        <a href="{% provider_login_url 'kakao' %}" class="btn btn-warning rounded-pill col-6 mt-3">카카오톡 회원가입</a>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content%}

<div class="account_delete_base">
    <div>
        <h4>회원탈퇴</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}

<div>
    <div class="account_detail_base">
        
        {% if target_user.profile %}
        <img style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem;" src="{{ target_user.profile.image.url }}" alt="">
        <h2>
            {{ target_user.profile.nickname }}
            {% if target_user == user %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                프로필 수정
            </a>
            <h5 class="profile_message">
                {{ target_user.profile.message }}
            </h5>   
            {% endif %}
        </h2>
        {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
            <h2>
                프로필 생성     
            </h2>
        </a>
        {% else %}
        <h2>
            프로필을 설정해 주세요
        </h2>
        {% endif %}
        {% endif %}
        {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=user.pk %}">
            <p>
                회원정보 변경
            </p>
        </a>
        <a href="{% url 'accountapp:delete' pk=user.pk %}">
            <p>
                회원탈퇴
            </p>
        </a>
        {% endif %}
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}
<div class="account_login_base">
    <div>
        <h4>로그인</h4>
    </div>
    <div style="margin-top: 2rem;">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary rounded-pill col-6 mt-5">
        </form>
    </div>
    <div>
        <a href="{% provider_login_url 'kakao' %}" class="btn btn-warning rounded-pill col-6 mt-3">카카오톡 로그인</a>
    </div>
    <hr>
    <div>
        <a href="{% url 'accountapp:create' %}">아직 계정이 없으신가요? <strong>가입하기</strong></a>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/test.html
{% extends 'base.html' %}


{% block content %}

<div style="border-radius: 1rem; margin: 2rem; font-size: 2rem; text-align: center;">
    <h1 style="font-family:'Do Hyeon', sans-serif;">
        TEST LIST
    </h1>
    <form action="{% url 'accountapp:test' %}" method="post">
        {% csrf_token %} <!--장고에서 제공하는 보안기능들 중 하나 // 장고에서 POST를 이용해 서버에 요청을 보낼때는 csrf_token을 form안에 항상 명시해줘야 한다 -->
        <div>
            <input type="text" name="test_input">
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="POST">
        </div>
    </form>

    {% if new_text_list %}
        {% for new_text in new_text_list %}
    <h4>
        {{ new_text.text }}
    </h4>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content%}

<div class="account_update_base">
    <div>
        <h4>회원정보 변경</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}