accountapp/urls.py
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, test
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accountapp'

urlpatterns = [
    path('test/', test, name='test'),                           # 두 번째 인자 test는 함수형 view => 이 경우에는 해당 함수이름을 바로 써서 넣어주면 되지만
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),  # class based view는 as_view()를 적어줘야 한다
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleListView, ArticleUpdateView, ArticleDeleteView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

mureojwo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("accounts/", include("allauth.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("commentapp/", include("commentapp.urls")),
    path("likes/", include("likeapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}


    <hr class="base_line_color">


    {% block content %}

    {% endblock %}


    <hr class="base_line_color">


    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="footer_base">
    <div class="footer_font_size">
        <span>공지사항 |</span>
        <span>제휴문의 |</span>
        <span>서비스 소개</span>
    </div>
    <div class="footer_logo_margin">
        <h5 class="footer_logo">Mureojwo</h5>
    </div>
</div>

templates/head.html
<head>
{% load static %}
    
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mureojwo</title>

    <!-- BootStrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Google Fonts Link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">

    <!-- Google Material Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- Default CSS Link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

</head>

templates/header.html
<div class="mureojwo_header">
    <div>
        <h1 class="mureojwo_logo">물어줘</h1>
    </div>
    <div>
        <span class="nav_margin">어종</span>
        <span class="nav_margin">포인트</span>
        <a href="{% url 'articleapp:list' %}" class="nav_margin">
            <span>게시글</span>
        </a>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="nav_margin">
            <span>로그인</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="nav_margin">
            <span>마이페이지</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="nav_margin">
            <span>로그아웃</span>
        </a>
        {% endif %}
    </div>
</div>